CREATE TABLE "tasks" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT NOT NULL, "name" TEXT NOT NULL, "priority" INTEGER(1), "completed" DATETIME, "due" DATETIME, "list" INTEGER NOT NULL, "created" DATETIME DEFAULT CURRENT_DATE, "updated" DATETIME DEFAULT CURRENT_DATE, "rtm_id" INTEGER, "synced" DATETIME, "deleted" DATETIME);

CREATE TABLE "lists" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT NOT NULL, "name" TEXT NOT NULL, "created" DATETIME DEFAULT CURRENT_DATE, "updated" DATETIME DEFAULT CURRENT_DATE, "rtm_id" INTEGER, "synced" DATETIME, "deleted" DATETIME);
